### PR TITLE
Osmo challenges 

### PR DESCRIPTION
**Pull request by giansalex**
> Updated 6/16
 
Testnet deployments (osmo test-4 <-> juno uni-3)

- Query Spot Price

Network| Contract |
-|-|
Juno | https://blueprints.juno.giansalex.dev/#/contracts/juno12kztahg9pf6p5fjxypw90v7920wvd2nx6rpfnjp3n3ajhwf277ps2eerdp |
Osmo | https://osmosis-contracts.web.app/#/contracts/osmo1emxpwsqpf09zmnk8rjym4a66fdmpnx04gdw7fx8rpv5rsq3jyghsv9l33l |

- Swap, Add/Remove Liquidity, Bond/Unbond

Network| Contract |
-|-|
Juno | https://blueprints.juno.giansalex.dev/#/contracts/juno12wfzft2ykl0rxpm8sku2ydt2ee872xr2r29ehdalh94a30k5z6cs9yu9cv |
Osmo | https://osmosis-contracts.web.app/#/contracts/osmo1lzuevjs0t4ywjgg0kn9lcdwuvsksxq3uvgaam44lrqhutjk5v3nqr2hehr |

UI Demo
https://dapps.juno.giansalex.dev/osmo/#/

### CODE REVIEW

**Comment by giansalex** [comment]
Contracts were successfully deployed to current osmosis testnet. 
- [Proposal 1](https://testnet-rest.osmosis.zone/cosmos/gov/v1beta1/proposals/152)
- [Proposal 2](https://testnet-rest.osmosis.zone/cosmos/gov/v1beta1/proposals/153)

Contracts:

Network| Contract (IBC query) |
-|-|
uni-2 | https://blueprints.juno.giansalex.dev/#/contracts/juno1z6yx6uy2dm838c5yq4205c69e5sv0fjqqyau5fg67r7mkkf6n2uqcjdn9u |
osmo-test-4 | https://osmosis-contracts.web.app/#/contracts/osmo14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9sq2r9g9 |

Network| Contract (Swap, Liquidity) |
-|-|
uni-2 | https://blueprints.juno.giansalex.dev/#/contracts/juno1ldmyzqcg0rx0q8yru23lzwzl2dnhlsh923qff3kcgtl4zlhjs9yqqwpnsc |
osmo-test-4 | https://osmosis-contracts.web.app/#/contracts/osmo1nc5tatafv6eyq7llkr2gv50ff9e22mnf70qgjlv737ktmt4eswrqvlx82r |

> Blueprints has been improved to include more detail on IBC txs (Rcv, Ack)

**Comment by JakeHartnell** [comment]
Awesome, can you make sure the source code for the contracts is linked here? Looking good though. @dimiandre have a look.

**Comment by giansalex** [comment]
@JakeHartnell yes, will be public, first i'll update docs, tests, .. 
I deployed a UI for these ibc contracts: https://dapps.juno.giansalex.dev/osmo/ 
image

- Can get osmos testnet tokens in the [faucet channel](https://discord.com/channels/798583171548840026/911309363464007741)
- [Osmosis Testnet UI](https://testnet.osmosis.zone/)
> ** keplr has an issue to "add cw20 token". `github.com/chainapsis/keplr-wallet/pull/338`

**Comment by giansalex** [comment]
Issues found in this process
```
- https://github.com/CosmWasm/cw-plus/issues/662
- https://github.com/cosmos/ibc-go/issues/894
- https://github.com/osmosis-labs/osmosis/pull/1115
- https://github.com/CosmWasm/cw-plus/issues/687
```

**Comment by giansalex** [comment]
Currently added support to lock/unlock tokens and claim rewards, but i found a problem, it is an issue that also affects authz for modules: lockup, superfluid, incentives.

the issue has been fixed and will be included in next version (osmosis v8 probably). 
```
https://github.com/osmosis-labs/osmosis/issues/1093
```

- [Osmosis bindings](https://github.com/confio/osmosis-bindings) (by cosmwasm team), are also affected, although it does not yet have support for lockup module.
- Same problem for [ICA](https://github.com/cosmos/ibc-go/blob/v3.0.0/modules/apps/27-interchain-accounts/host/keeper/relay.go#L119) (ErrInvalidRoute)

**Comment by giansalex** [comment]
Testing Juno-halt in osmosis testnet (no cosmwasm patched)
- Juno tx: [75D21A37260BC633B96F2F08B0035CAD02F85576F9630AE9584C8D337A28BFC2](https://blueprints.juno.giansalex.dev/#/transactions/75D21A37260BC633B96F2F08B0035CAD02F85576F9630AE9584C8D337A28BFC2) 
- Osmos Tx: [F8EC7D6C4BA18FF709AEF803EB5A6F5B5EA08FCF9A924A6A6B181EFEC1F5AA07](https://osmosis-contracts.web.app/#/transactions/F8EC7D6C4BA18FF709AEF803EB5A6F5B5EA08FCF9A924A6A6B181EFEC1F5AA07)

not halt because the osmosis contract already included the security patch, I only updated the Juno contract to add the dangerous query.

**Comment by giansalex** [comment]
Bond/Unbond/Claim deployed contracts, it is using a local osmo testnet, because osmosis testnet does not have a patch for the lockup issue.

Network| Contract (IBC lockups) |
-|-|
uni-2 | https://blueprints.juno.giansalex.dev/#/contracts/juno1hmvfcnl3np52a3lwealxdwds5qgyvgjqj59npjzh8nr8sq6h7jgslcudy5 |
osmo-local | https://lcd.osmo.giansalex.dev/cosmwasm/wasm/v1/contract/osmo1trgwnsk08md5yxf3yp5ex975d5jyyjmz8uhvvwuv3vr4r3n8jr7qdsvr4d |

I also built a new UI demo for bond/unbond/claim actions , https://dapps.juno.giansalex.dev/earn/#/locks
image

image

**Comment by giansalex** [comment]
@JakeHartnell @dimiandre I share the source code repos of all contracts, all challenges are included.

- Osmosis
https://github.com/disperze/cw-osmo

- Juno
 https://github.com/giansalex/cw-osmo-price
 https://github.com/giansalex/cw-osmo-swap

All contracts are fully functional, as you can see in the demo UI,  if anything is missing, please let me know.

I also sent a draft proposal to the osmosis team a week ago, I am waiting for a response.

**Comment by JakeHartnell** [comment]
Closing for now, partially paid out as this was a good effort for a very difficult challenge. Looking forward to what you do next!

**Pull request closed without merging**
