### PR TITLE
CW20 IBC Challenge

### PR DESCRIPTION
**Pull request by VitalyVolozhinov**
Creating a step-by-step tutorial on how to sent CW20 tokens over IBC.

### CODE REVIEW

**Comment by JakeHartnell** [comment]
Can you please:
- Make a separate repo for this documentation?
- Transfer a Juno mainnet cw20 to Osmosis mainnet and back providing block explorer links with as much proof as possible

I'm considering this the first submission, but If I don't have the above by Tuesday, will open it up again. Best of luck. : )

**Comment by franono** [comment]
@JakeHartnell I've moved the guide to https://github.com/franono/juno-docs

Using account on juno mainnet: juno1fdtnpl9m0aq5wrjq467atk6tlukhqvyre8hyqg

1. cw20_ics20.wasm deployed at code 13: https://www.mintscan.io/juno/txs/4AA14A399901C163D9571621370927EAD11A3CD4267835BFD71144E602BC2B32
2. Instantiated cw20_ics20 contract: juno1nkahswfr8shg8rlxqwup0vgahp0dk4x8w6tkv3rra8rratnut36sqj48re with tx https://www.mintscan.io/juno/txs/35859858A42DBB22C36FBFB9EE5A509EDC8F7D86B6A76D38EB5648CDA8696EC4
3. Deployed cw20 base  https://www.mintscan.io/juno/txs/B87DAC50519E24393E7918CE7668D57230168E52E49F0B5F5A6B58103C6F1758 at
code 14
4. Instantiated cw20 base with https://www.mintscan.io/juno/txs/5F8DFC86705AF95A5B296D5E9D0B445C393F73C5B4C012218363100047DD80C6
5. Sent tokens to cw20_ics20, transferring over channel-25 https://www.mintscan.io/juno/txs/9175FDC0DCECA3DBCF0AC9345F384287EBE6294E8046600FA596991CC3E11DB6
6. Receive on osmosis account osmo1emwhfaua8p8rk4w8889hzevtwkphxjc7y3nrsf https://www.mintscan.io/osmosis/txs/58E26814DAD6C86DE1E7F54CF59596FC9A85246759DD61C3DD92D9E6A2491653
7. Send tokens back over IBC to juno account https://www.mintscan.io/osmosis/txs/827E21A02B09A26119D4DB8FAD58687DC0D5086220E0C7E38F3F1791027084FA
8. Receive on account juno1fdtnpl9m0aq5wrjq467atk6tlukhqvyre8hyqg https://www.mintscan.io/juno/txs/E1C69A92F4F24AD7AF8AD0EEF9F8076ACFDB11FE9BAEA6A0C0B0349DF6C70E1D

**Comment by JakeHartnell** [comment]
Very cool, could you please clean up this PR so that it just adds your address to the `README.md` table.

@dimiandre, please have a look at this.

**Comment by VitalyVolozhinov** [comment]
@JakeHartnell PR cleaned up

**Comment by JakeHartnell** [comment]
> @JakeHartnell PR cleaned up

Still has merge conflicts. : )

**Comment by JakeHartnell** [comment]
@dimiandre, please verify.

**Comment by dimiandre** [comment]
Thanks for testing! Seems good to me

**Comment by franono** [comment]
@JakeHartnell juno1jax0gp2kczt3mmp68xt967z92yjnmrdm6ujrew as in the PR, thanks

**Pull request merged**
