### PR TITLE
Query price over IBC

### PR DESCRIPTION
**Pull request by giansalex**
This pr is to share a demo between JUNO UNI testnet and custom osmosis node (gamm IBC).

image

IBC channel
```json
{
      "state": "STATE_OPEN",
      "ordering": "ORDER_UNORDERED",
      "counterparty": {
        "port_id": "gamm",
        "channel_id": "channel-0"
      },
      "connection_hops": [
        "connection-0"
      ],
      "version": "gamm-1",
      "port_id": "wasm.juno1d2r4s2q8kumpmvx6dyj77klhgm5e6fs9njmmz6ye7ukqa77ddtdsafda4d",
      "channel_id": "channel-0"
}
```

Demo
- Osmosis UI: https://osmosis-ibc.web.app/?from=JUNOX&to=HAZ
   - you can deposit JUNOX, cw20 token
   - use small amounts (ex: 0.1), low liquidity
- Contract UI: https://dapps.juno.giansalex.dev/osmo/ (query price)

### CODE REVIEW

**Comment by JakeHartnell** [comment]
Awesome! Can you open source the contract code and link it here? That's an important part of the bounty. :slightly_smiling_face:

**Comment by giansalex** [comment]
Current demo was made with an ibc contract and a custom ibc module, but since this proposal was approved https://www.mintscan.io/osmosis/proposals/107 , 
i think the best solution is migrate the ibc module to an ibc contract as well

**Comment by JakeHartnell** [comment]
> Awesome! Can you open source the contract code and link it here? That's an important part of the bounty. slightly_smiling_face

Still waiting  on contract code. :upside_down_face:

**Comment by giansalex** [comment]
@JakeHartnell , this is the source code https://github.com/giansalex/cw-osmo-price

Contract address on Uni Testnet: 
- [juno1hau40wepfjrvu7z549j3zwz955agv0em7wz8p9nkrwczf84ut0eshp4wxv](https://blueprints.juno.giansalex.dev/#/contracts/juno1hau40wepfjrvu7z549j3zwz955agv0em7wz8p9nkrwczf84ut0eshp4wxv)

**Comment by VitalyVolozhinov** [comment]
Did you do any custom modifications to the Osmosis node?

**Comment by verminator23** [comment]
@VitalyVolozhinov I think he just created a custom Osmosis IBC module that returns price info from the GAMM module. This is a great start, but isn't a representative example of how this would be done in production, given upcoming updates to Osmosis.

Osmosis will soon have cosmwasm bindings for interacting with the AMM. So the Osmosis price fetching logic should happen as a cosmwasm contract instead of an IBC module.

Additionally, fetching regular spot price can be easily manipulated, and shouldn't be used in production. The Osmosis team is working on making a more secure TWAP oracle that can be leveraged in cosmwasm contracts.

**Comment by JakeHartnell** [comment]
> @JakeHartnell , this is the source code https://github.com/giansalex/cw-osmo-price
> 
> Contract address on Uni Testnet:
> 
> * [juno1hau40wepfjrvu7z549j3zwz955agv0em7wz8p9nkrwczf84ut0eshp4wxv](https://blueprints.juno.giansalex.dev/#/contracts/juno1hau40wepfjrvu7z549j3zwz955agv0em7wz8p9nkrwczf84ut0eshp4wxv)

Re @verminator23's comment is this using a custom IBC module? Has that been merged? If not where is the code for that? Would this work with mainnet Osmosis and Juno chains?

**Comment by VitalyVolozhinov** [comment]
> > @JakeHartnell , this is the source code https://github.com/giansalex/cw-osmo-price
> > Contract address on Uni Testnet:
> > 
> > * [juno1hau40wepfjrvu7z549j3zwz955agv0em7wz8p9nkrwczf84ut0eshp4wxv](https://blueprints.juno.giansalex.dev/#/contracts/juno1hau40wepfjrvu7z549j3zwz955agv0em7wz8p9nkrwczf84ut0eshp4wxv)
> 
> Re @verminator23's comment, is this using a custom IBC module? Has that been merged? If not where is the code for that? Would this work with mainnet Osmosis and Juno chains?

I believe it's not possible to query data over IBC yet from CosmWasm to a Module. I think we have to wait for ICA to be implemented in Osmosis and Juno chains to complete these bounties correctly.

**Comment by giansalex** [comment]
@JakeHartnell, the challenge is with a custom IBC module, do you need anything else?

**Comment by JakeHartnell** [comment]
> @JakeHartnell, the challenge is with a custom IBC module, do you need anything else?

Has that module been merged into Osmosis? :upside_down_face: 

This needs to work with mainnet Juno and mainnet Osmosis.

**Comment by giansalex** [comment]
but will osmosis accept a custom module? and if they don't accept it, these challenges are unviable.

**Comment by JakeHartnell** [comment]
> but will osmosis accept a custom module? and if they don't accept it, these challenges are unviable.

Worth a shot. Can work out a custom payout with @dimiandre if they are unviable. Part of the reason the bounties are high is that there are lots of pieces.

**Comment by giansalex** [comment]
@JakeHartnell yes, it has been several steps, develop contract & ibc module, deploy the custom osmosis node (update osmosis frontend to allow cw20 deposits, configure pools, liquidity), configure relayer service, develop contract UI demo,
The only thing that would be missing is to integrate the ibc module in osmosis, but that is out of my reach. 

The challenge will be completed when cosmwasm is enabled in osmosis mainnet?

**Comment by giansalex** [comment]
I was also working on the swap challenge, and i was able to get it to work.
image

**Comment by JakeHartnell** [comment]
> The only thing that would be missing is to integrate the ibc module in osmosis, but that is out of my reach.

Can you give it your best effort? At least submit a PR and link it here? 

If anything, it's an important path for discussion. If they are against adding IBC modules for these things, and want to go purely the CosmWasm route then we have our answer.

**Comment by dimiandre** [comment]
Definitely an awesome job. Can you share access to the code? 

And as jake said would be a big plus if you can provide a PR to osmosis repository, then we can help communicating with osmosis community to take this on mainnet. 

For bounty payments maybe we can split in phases

**Comment by giansalex** [comment]
ok, i will prepare the pull request

**Comment by giansalex** [comment]
For osmosis mainnet,  i need to wait for [IBC queries](https://github.com/cosmos/ibc/discussions/605)

**Comment by JakeHartnell** [comment]
> For osmosis mainnet, i need to wait for cosmwasm or [IBC queries](https://github.com/cosmos/ibc/discussions/605)

Saw this. Thanks for the investigation, we're going to do a partial payout for this as it's blocked. Still this was very helpful. :pray:

**Comment by giansalex** [comment]
I am sharing the Swap module used in another example, it's an IBC module as @JakeHartnell suggested at some point, based on the middleware approach, passed all ibc-transfer tests.
https://github.com/disperze/ibc-osmo/tree/master/x/intergamm

There is also a branch for liquidity pool 
https://github.com/disperze/ibc-osmo/tree/pools

**Pull request merged**
